### ISSUE TITLE
How to output with comments/variations removed?

### ISSUE THREAD

**Issue by xxaix** [louchesprocket/pgnutil#1]
Given an input such as this:

```
[Event "Live Chess"]
[Site "Chess.com"]
[Date "2020.08.13"]
[Round "-"]
[White "karankunaal"]
[Black "wismahobby"]
[Result "0-1"]
[CurrentPosition "r1bqkbnr/pp1p1ppp/2n1p3/2Q5/4P3/8/PPP2PPP/RNB1KBNR w KQkq -"]
[Timezone "UTC"]
[ECO "B21"]
[ECOUrl "https://www.chess.com/openings/Sicilian-Defense-Smith-Morra-Gambit-2...cxd4-3.Qxd4-Nc6"]
[UTCDate "2020.08.13"]
[UTCTime "23:01:57"]
[WhiteElo "100"]
[BlackElo "319"]
[TimeControl "300"]
[Termination "wismahobby won by resignation"]
[StartTime "23:01:57"]
[EndDate "2020.08.13"]
[EndTime "23:02:11"]
[Link "https://www.chess.com/live/game/5294311587"]

1. e4 {[%clk 0:04:59.9]} 1... c5 {[%clk 0:04:58]} 2. d4 {[%clk 0:04:58.6]} 2... cxd4 {[%clk 0:04:56.7]} 3. Qxd4 {[%clk 0:04:57.1]} 3... Nc6 {[%clk 0:04:55.2]} 4. Qc5 {[%clk 0:04:55.8]} 4... e6 {[%clk 0:04:53.6]} 0-1
```

I would like the clock, comments, and variations removed. I want the output to simply be the headers, and the moves. Is there a way to do this?

**Comment by louchesprocket** [comment]
There are two different ways to interpret your question: 1) can you output the original PGN file, but with comments removed; and 2) can you output a delimiter-separated list of all fields (including moves), but without comments. The answer to question 1) is no, but the answer to question 2) is yes. For example, the options "-s white,black,date,event,moves" will output the "White," "Black," "Date," and "Event" tags plus the move list. Please advise if you are asking question 1).

**Comment by louchesprocket** [comment]
Belated update: with the "replace" ("-r") option fixed, it is now possible to strip comments. Please see the README.
